services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: metatasks
      POSTGRES_USER: metatasks
      POSTGRES_PASSWORD: metatasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metatasks -d metatasks || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    # Wait for Postgres to become available, run migrations, then start Django
    command: >-
      bash -c "
        python scripts/wait_for_db.py && \
        echo 'Applying migrations...' && python manage.py migrate --noinput && \
        echo 'Starting server...' && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://metatasks:metatasks@db:5432/metatasks
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DB_NAME=metatasks
      - DB_USER=metatasks
      - DB_PASSWORD=metatasks
      - DB_HOST=db
      - DB_PORT=5432
      - LOG_LEVEL=INFO

volumes:
  postgres_data:
