# Generated by Django 5.0.14 on 2025-10-05 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_users', models.IntegerField(help_text='Maximum number of users (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_workflows', models.IntegerField(help_text='Maximum number of workflows (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_work_items', models.IntegerField(help_text='Maximum number of work items (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_storage_bytes', models.BigIntegerField(help_text='Maximum storage in bytes (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('has_api_access', models.BooleanField(default=True)),
                ('has_integrations', models.BooleanField(default=False)),
                ('has_advanced_workflows', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('workflows_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_items_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='licensing.plan')),
            ],
            options={
                'verbose_name_plural': 'Usages',
            },
        ),
    ]
